#!/usr/bin/env python3
"""Redraw the block diagrams / flowcharts of chosen slides as editable TikZ.

Works on a Beamer project made by pptx2beamer.py: for every diagram on a chosen slide
it writes diagrams/slide_<i>_diagram_<j>.tex and, in slides/slide_<i>.tex, replaces
\\includegraphics{slide_<i>_image_<j>} by \\input{diagrams/slide_<i>_diagram_<j>}.

Usage:
    python pptx2tikz.py deck.pptx --slides 22,50 [--project deck_beamer]
    python pptx2tikz.py deck.pptx --slides slide_22.tex slide_50.tex
"""

import argparse
import math
import os
import re
import sys

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.oxml.ns import qn

import pptx2beamer as pb

STYLES = r"""% Styles for the TikZ diagrams (generated by pptx2tikz.py)
\usetikzlibrary{arrows.meta, calc, decorations.pathreplacing}
\tikzset{>=Latex,
  block/.style={draw, minimum width=1.4cm, minimum height=0.9cm},
  sum/.style={draw, circle, minimum size=0.5cm, inner sep=0pt},
  box/.style={draw, align=center, text width=2.6cm, minimum height=1cm},
  sign/.style={font=\scriptsize, inner sep=1pt},
  branch/.style={circle, fill, inner sep=1pt}}
"""

RECT_SHAPES = {"rect", "roundRect", "flowChartProcess", "flowChartAlternateProcess",
               "snip1Rect", "round1Rect", "round2SameRect", "flowChartPredefinedProcess"}
SUM_SHAPES = {"ellipse", "flowChartSummingJunction", "flowChartOr", "flowChartConnector"}
SIGNS = {"+": "+", "-": "-", "\u2212": "-", "\u00b1": r"\pm"}
COMPASS = ["east", "north east", "north", "north west", "west", "south west", "south", "south east"]


# --------------------------------------------------------------------------
# Reading the shapes
# --------------------------------------------------------------------------

class Item:
    """A flattened shape. Geometry in cm, y axis pointing up."""

    def __init__(self, kind, sid, x, y, w, h):
        self.kind, self.sid = kind, sid          # node | edge | label | picture | other
        self.x, self.y, self.w, self.h = x, y, w, h
        self.prst, self.text, self.name, self.style = "", "", "", ""
        self.lines = []                          # (raw text, paragraph index, count, align)
        self.points = []                         # edges: polyline
        self.start = self.end = None             # edges: glued shape ids
        self.arrow = "-"
        self.signs = []                          # sums: (sign, x, y) estimated positions

    @property
    def cx(self):
        return self.x + self.w / 2

    @property
    def cy(self):
        return self.y - self.h / 2              # (x, y) is the top-left corner


def _adj(el):
    vals = {}
    geom = el.find(".//" + qn("a:prstGeom"))
    if geom is not None:
        for gd in geom.iter(qn("a:gd")):
            m = re.match(r"val\s+(-?\d+)", gd.get("fmla", ""))
            if m:
                vals[gd.get("name")] = int(m.group(1)) / 100000
    return vals


def connector_path(prst, adj, w, h):
    """Polyline of a (bent) connector in its local box, from start to end (y down)."""
    a1, a2, a3 = adj.get("adj1", 0.5), adj.get("adj2", 0.5), adj.get("adj3", 0.5)
    if prst == "bentConnector2":
        return [(0, 0), (w, 0), (w, h)]
    if prst == "bentConnector3":
        return [(0, 0), (w * a1, 0), (w * a1, h), (w, h)]
    if prst == "bentConnector4":
        return [(0, 0), (w * a1, 0), (w * a1, h * a2), (w, h * a2), (w, h)]
    if prst == "bentConnector5":
        return [(0, 0), (w * a1, 0), (w * a1, h * a2), (w * a3, h * a2), (w * a3, h), (w, h)]
    return [(0, 0), (w, h)]  # straight connectors and lines (curved ones approximated)


def _place(points, xfrm, x, y, w, h):
    """Apply flips and rotation of the shape's xfrm, then move to (x, y) (EMU, y down)."""
    flip_h = xfrm is not None and xfrm.get("flipH") == "1"
    flip_v = xfrm is not None and xfrm.get("flipV") == "1"
    rot = math.radians(int(xfrm.get("rot", 0)) / 60000) if xfrm is not None else 0
    out = []
    for px, py in points:
        if flip_h:
            px = w - px
        if flip_v:
            py = h - py
        dx, dy = px - w / 2, py - h / 2
        px = w / 2 + dx * math.cos(rot) - dy * math.sin(rot)
        py = h / 2 + dx * math.sin(rot) + dy * math.cos(rot)
        out.append((x + px, y + py))
    return out


def _inline(tex):
    """Display math -> inline math, so the text fits in a node."""
    return re.sub(r"\\\[ ?(.*?) ?\\\]", r"$\1$", tex).strip()


def _paragraph_texts(shape):
    out = []
    for p in shape.text_frame.paragraphs:
        tex = _inline(pb.paragraph_latex(p, shape.part, line_break=" "))
        raw = "".join(t.text or "" for t in p._p.iter(qn("a:t"), pb.M + "t"))
        algn = p._p.pPr.get("algn") if p._p.pPr is not None else None
        out.append((tex, raw, algn))
    return out


class Reader:
    def __init__(self, prs):
        self.prs = prs
        # scale PowerPoint's slide onto the Beamer page, so text sizes match
        ratio = prs.slide_width / prs.slide_height
        beamer_w = 16.0 if abs(ratio - 16 / 9) < 0.05 else 16.0 if abs(ratio - 1.6) < 0.03 else 12.8
        self.k = beamer_w / (prs.slide_width / 360000) / 360000   # EMU -> cm

    def flatten(self, container, shapes, transform, out):
        for shape in pb.iter_shapes(container, shapes):
            try:
                x, y, w, h = transform(shape.left or 0, shape.top or 0,
                                       shape.width or 0, shape.height or 0)
            except TypeError:
                continue
            el = shape._element
            if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
                self.flatten(el, shapes, pb.SlideConverter._group_transform(shape, transform), out)
                continue
            k = self.k
            item = Item("other", shape.shape_id, x * k, -y * k, w * k, h * k)
            geom = el.find(".//" + qn("a:prstGeom"))
            item.prst = geom.get("prst") if geom is not None else ""
            out.append(item)

            if pb._has_image(shape) or shape.shape_type == MSO_SHAPE_TYPE.MEDIA:
                item.kind = "picture"
                continue
            is_line = (shape.shape_type == MSO_SHAPE_TYPE.LINE
                       or el.tag == qn("p:cxnSp") or item.prst.endswith("Connector1")
                       or item.prst in ("line", "straightConnector1") or "Connector" in item.prst)
            if is_line:
                item.kind = "edge"
                xfrm = el.find(".//" + qn("a:xfrm"))
                local = connector_path(item.prst, _adj(el), w, h)
                item.points = [(px * k, -py * k) for px, py in _place(local, xfrm, x, y, w, h)]
                for tag, attr in (("a:stCxn", "start"), ("a:endCxn", "end")):
                    c = el.find(".//" + qn(tag))
                    if c is not None:
                        setattr(item, attr, int(c.get("id")))
                ln = el.find(".//" + qn("a:ln"))
                head = tail = False
                if ln is not None:
                    he, te = ln.find(qn("a:headEnd")), ln.find(qn("a:tailEnd"))
                    head = he is not None and he.get("type", "none") != "none"
                    tail = te is not None and te.get("type", "none") != "none"
                item.arrow = {(False, True): "->", (True, False): "<-", (True, True): "<->"}.get((head, tail), "-")
                continue

            paras = _paragraph_texts(shape) if shape.has_text_frame else []
            item.text = r" \\ ".join(t for t, _, _ in paras if t)
            item.lines = [(raw, i, len(paras), algn) for i, (_, raw, algn) in enumerate(paras)]
            if shape.shape_type == MSO_SHAPE_TYPE.TEXT_BOX or (not item.prst and item.text):
                item.kind = "label" if item.text else "empty"
            elif item.prst in RECT_SHAPES:
                item.kind, item.style = "node", "block"
            elif item.prst in SUM_SHAPES:
                item.kind, item.style = "node", "sum"

    def diagrams(self, slide, slide_index):
        """[(j, [Item])] for every diagram cluster pptx2beamer found on the slide."""
        conv = pb.SlideConverter(self.prs, None, [], diagrams=True)
        state = conv.prepare(slide, slide_index, is_first_title=False)
        pictures = [e for e in state["elements"] if e.kind == "image" and e.render is None]
        result = []
        for j, el in enumerate(pb.image_order(state["elements"]), start=1):
            if el.render is None:
                continue
            if any(p.x < el.right and el.x < p.right and p.y < el.bottom and el.y < p.bottom
                   for p in pictures):
                result.append((j, None))  # annotations drawn over a picture
                continue
            tops = [s for s in pb.iter_shapes(slide.shapes._spTree, slide.shapes)
                    if s.shape_id in el.ids]
            items = []
            identity = lambda x, y, w, h: (x, y, w, h)
            for top in tops:
                box = top._element
                if box.getparent().tag == pb.MC + "Choice":  # keep the AlternateContent wrapper
                    box = box.getparent().getparent()
                self.flatten([box], slide.shapes, identity, items)  # just this shape
            result.append((j, items))
        return result


# --------------------------------------------------------------------------
# Building the TikZ picture
# --------------------------------------------------------------------------

def _snap_groups(values, tol):
    """Map each value to the mean of its cluster (values closer than tol), rounded."""
    order = sorted(set(values))
    mapping, group = {}, []
    for v in order + [None]:
        if v is not None and (not group or v - group[-1] <= tol):
            group.append(v)
            continue
        mean = round(sum(group) / len(group) * 20) / 20 if group else 0
        for g in group:
            mapping[g] = mean
        group = [v] if v is not None else []
    return mapping


def _name_from_text(text, used, fallback):
    plain = re.sub(r"\\[a-zA-Z]+|[${}()^\\ ]", " ", text)
    m = re.match(r"\s*([A-Za-z])[\s_]*(\d*)", plain)
    base = (m.group(1) + m.group(2)) if m and len(re.sub(r"\s", "", plain)) <= 12 else fallback
    name, n = base, 2
    while name in used:
        name, n = f"{base}{n}", n + 1
    used.add(name)
    return name


def _fmt(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _pt(p):
    return "(%s,%s)" % (_fmt(p[0]), _fmt(p[1]))


class Diagram:
    def __init__(self, items):
        self.items = items
        self.nodes = {i.sid: i for i in items if i.kind == "node"}
        self.edges = [i for i in items if i.kind == "edge"]
        self.labels = [i for i in items if i.kind == "label"]
        self.others = [i for i in items if i.kind == "other"]
        self.used = set()
        self.lines = []

    # ---- analysis -----------------------------------------------------------

    def classify_nodes(self):
        for n in self.nodes.values():
            if n.style == "block":
                plain = re.sub(r"\\[a-zA-Z]+|[${}\\ ]", "", n.text)
                if len(plain) > 12 or n.text.count("$") == 0 and len(plain) > 4:
                    n.style = "box"

    def merge_labels(self):
        """Text boxes on top of a node become its text (sums: its signs)."""
        for lab in list(self.labels):
            for n in self.nodes.values():
                inside = n.x - 0.1 < lab.cx < n.x + n.w + 0.1 and n.y - n.h - 0.1 < lab.cy < n.y + 0.1
                near_sum = n.style == "sum" and math.hypot(lab.cx - n.cx, lab.cy - n.cy) < 1.6 * max(n.w, 0.3)
                sign = _plain(lab.text) in SIGNS
                if n.style == "sum" and sign and (inside or near_sum):
                    n.signs.append((SIGNS[_plain(lab.text)], lab.cx, lab.cy))
                    self.labels.remove(lab)
                    break
                if inside and n.style != "sum" and not n.text:
                    n.text = lab.text
                    self.labels.remove(lab)
                    break
        for n in self.nodes.values():  # signs typed inside the ellipse
            if n.style != "sum":
                continue
            for raw, i, count, algn in n.lines:
                s = raw.strip()
                if s in SIGNS:
                    fy = n.y - n.h * (i + 0.5) / max(count, 1)
                    lead = len(raw) - len(raw.lstrip())
                    fx = n.cx + (0.3 * n.w if algn == "r" or lead >= 2 else
                                 0 if algn == "ctr" else -0.3 * n.w)
                    n.signs.append((SIGNS[s], fx, fy))
            n.text = ""

    def snap(self):
        """Align node/label centres on shared rows and columns."""
        things = list(self.nodes.values()) + self.labels
        xs = _snap_groups([t.cx for t in things], 0.25)
        ys = _snap_groups([t.cy for t in things], 0.25)
        for t in things:
            t.x, t.y = xs[t.cx] - t.w / 2, ys[t.cy] + t.h / 2
        # move the origin to the diagram's top-left corner (nicer numbers to edit)
        everything = things + self.edges + self.others
        x0 = round(min(min(p[0] for p in e.points) if e.points else e.x for e in everything) * 2) / 2
        y0 = round(max(max(p[1] for p in e.points) if e.points else e.y for e in everything) * 2) / 2
        for t in everything:
            t.x, t.y = t.x - x0, t.y - y0
            t.points = [(px - x0, py - y0) for px, py in t.points]
        for n in self.nodes.values():
            n.signs = [(s, sx - x0, sy - y0) for s, sx, sy in n.signs]
        xs = {k: v - x0 for k, v in xs.items()}
        ys = {k: v - y0 for k, v in ys.items()}
        # keep connector corners aligned with the snapped rows/columns
        for e in self.edges:
            pts = []
            for px, py in e.points:
                px = min(xs.values(), key=lambda v: abs(v - px)) if xs and min(abs(v - px) for v in xs.values()) < 0.2 else px
                py = min(ys.values(), key=lambda v: abs(v - py)) if ys and min(abs(v - py) for v in ys.values()) < 0.2 else py
                pts.append((px, py))
            e.points = pts

    def name_things(self):
        counters = {"sum": 0, "box": 0}
        for n in sorted(self.nodes.values(), key=lambda n: (-n.cy, n.cx)):
            if n.style == "sum":
                counters["sum"] += 1
                n.name = f"s{counters['sum']}"
                self.used.add(n.name)
            elif n.style == "box":
                counters["box"] += 1
                n.name = f"b{counters['box']}"
                self.used.add(n.name)
        for n in sorted(self.nodes.values(), key=lambda n: (-n.cy, n.cx)):
            if not n.name:
                n.name = _name_from_text(n.text, self.used, "B")
        for i, lab in enumerate(sorted(self.labels, key=lambda l: (-l.cy, l.cx)), start=1):
            lab.name = _name_from_text(lab.text, self.used, f"l{i}")

    # ---- geometry helpers -------------------------------------------------------

    def anchor(self, node, p):
        """TikZ reference for point p on the border of node."""
        dx, dy = p[0] - node.cx, p[1] - node.cy
        if node.style == "sum":
            idx = round(math.degrees(math.atan2(dy, dx)) / 45) % 8
            return f"({node.name}.{COMPASS[idx]})"
        # rectangle: nearest side, with an offset when not at the side's middle
        sides = {"east": abs(dx - node.w / 2), "west": abs(dx + node.w / 2),
                 "north": abs(dy - node.h / 2), "south": abs(dy + node.h / 2)}
        side = min(sides, key=sides.get)
        off = dy if side in ("east", "west") else dx
        if abs(off) < 0.15:
            return f"({node.name}.{side})"
        shift = "(0,%s)" % _fmt(off) if side in ("east", "west") else "(%s,0)" % _fmt(off)
        return f"($({node.name}.{side})+{shift}$)"

    def node_at(self, p, tol=0.2):
        for n in self.nodes.values():
            if n.x - tol <= p[0] <= n.x + n.w + tol and n.y - n.h - tol <= p[1] <= n.y + tol:
                return n
        return None

    def label_near(self, p, tol=0.6):
        best, dist = None, tol
        for lab in self.labels:
            ddx = max(lab.x - p[0], 0, p[0] - (lab.x + lab.w))
            ddy = max(lab.y - lab.h - p[1], 0, p[1] - lab.y)
            d = math.hypot(ddx, ddy)
            if d < dist:
                best, dist = lab, d
        return best

    @staticmethod
    def _on_segment(p, a, b, tol=0.12):
        if abs(a[0] - b[0]) < tol:
            return abs(p[0] - a[0]) < tol and min(a[1], b[1]) - tol <= p[1] <= max(a[1], b[1]) + tol
        if abs(a[1] - b[1]) < tol:
            return abs(p[1] - a[1]) < tol and min(a[0], b[0]) - tol <= p[0] <= max(a[0], b[0]) + tol
        return False

    # ---- output -------------------------------------------------------------------

    def end_ref(self, e, which, attached):
        idx = 0 if which == "start" else -1
        p = e.points[idx]
        glued = self.nodes.get(getattr(e, which)) or self.node_at(p, 0.05)
        if glued is not None:
            return self.anchor(glued, p)
        lab = self.label_near(p)
        if lab is not None:
            attached.add(lab.sid)
            box = Item("node", 0, lab.x, lab.y, lab.w, lab.h)
            box.name = lab.name
            return self.anchor(box, p)
        return _pt(p)

    def edge_path(self, e, attached, branch_points):
        pts = [p for i, p in enumerate(e.points) if i == 0 or math.dist(p, e.points[i - 1]) > 0.02]
        if len(pts) < 2:
            return None
        start = self.end_ref(e, "start", attached)
        end = self.end_ref(e, "end", attached)
        # a line starting on another line is a branch: draw the dot
        dot = any(o is not e and any(self._on_segment(pts[0], a, b) for a, b in zip(o.points, o.points[1:]))
                  for o in self.edges) and e.start is None
        path = start + (" node[branch]{}" if dot else "")
        mids = pts[1:-1]
        rest = []
        prev = pts[0]
        for i, c in enumerate(mids):
            is_last_corner = i == len(mids) - 1
            if is_last_corner and _axis(prev, c) and _axis(c, pts[-1]) and _axis(prev, c) != _axis(c, pts[-1]):
                rest.append(" -| " if _axis(prev, c) == "h" else " |- ")
                rest.append(end)
                prev = None
                break
            step = " -- ++(%s,%s)" % (_fmt(c[0] - prev[0]), _fmt(c[1] - prev[1]))
            if i == 0 and (e.start, round(pts[0][0], 1), round(pts[0][1], 1)) in branch_points:
                step += " node[branch]{}"
            rest.append(step)
            prev = c
        if prev is not None:
            rest.append(" -- " + end)
        return path + "".join(rest)

    def to_tikz(self):
        self.classify_nodes()
        self.merge_labels()
        self.snap()
        self.name_things()
        blocks = [n for n in self.nodes.values() if n.style == "block"]
        sums = [n for n in self.nodes.values() if n.style == "sum"]
        boxes = [n for n in self.nodes.values() if n.style == "box"]
        opts = []
        mw = mh = ms = bw = bh = None
        if blocks:
            mw, mh = _median([n.w for n in blocks]), _median([n.h for n in blocks])
            opts.append("block/.append style={minimum width=%scm, minimum height=%scm}" % (_fmt(mw), _fmt(mh)))
        if sums:
            ms = _median([n.w for n in sums])
            opts.append("sum/.append style={minimum size=%scm}" % _fmt(ms))
        if boxes:
            bw, bh = _median([n.w for n in boxes]), _median([n.h for n in boxes])
            opts.append("box/.append style={text width=%scm, minimum height=%scm}"
                        % (_fmt(max(bw - 0.3, 0.5)), _fmt(bh)))

        out = ["\\begin{tikzpicture}" + ("[%s]" % ", ".join(opts) if opts else "")]
        out.append("% blocks / sums")
        for n in sorted(self.nodes.values(), key=lambda n: (-n.cy, n.cx)):
            extra = ""
            if n.style == "block" and (abs(n.w - mw) > 0.25 * mw or abs(n.h - mh) > 0.25 * mh):
                extra = ", minimum width=%scm, minimum height=%scm" % (_fmt(n.w), _fmt(n.h))
            if n.style == "box" and (abs(n.w - bw) > 0.25 * bw or abs(n.h - bh) > 0.25 * bh):
                extra = ", text width=%scm, minimum height=%scm" % (_fmt(max(n.w - 0.3, 0.5)), _fmt(n.h))
            if n.style == "sum" and abs(n.w - ms) > 0.25 * ms:
                extra = ", minimum size=%scm" % _fmt(n.w)
            out.append("\\node[%s%s] (%s) at %s {%s};" % (n.style, extra, n.name, _pt((n.cx, n.cy)), n.text))

        # branch points: two edges leaving the same place, one turning off the other
        branch_points = set()
        for e in self.edges:
            for o in self.edges:
                if o is e or len(e.points) < 3 or e.start is None or e.start != o.start:
                    continue
                if math.dist(e.points[0], o.points[0]) < 0.1 and any(
                        self._on_segment(e.points[1], a, b) for a, b in zip(o.points, o.points[1:])):
                    branch_points.add((e.start, round(e.points[0][0], 1), round(e.points[0][1], 1)))

        attached = set()
        edge_lines = []
        for e in sorted(self.edges, key=lambda e: (-e.points[0][1], e.points[0][0])):
            path = self.edge_path(e, attached, branch_points)
            if path:
                edge_lines.append("\\draw[%s] %s;" % (e.arrow, path))

        if self.labels:
            out.append("% signals")
        for lab in sorted(self.labels, key=lambda l: (-l.cy, l.cx)):
            out.append("\\node (%s) at %s {%s};" % (lab.name, _pt((lab.cx, lab.cy)), lab.text))
        if edge_lines:
            out.append("% connections")
            out.extend(edge_lines)

        signs = self.sign_lines()
        if signs:
            out.append("% signs")
            out.extend(signs)
        for o in self.others:
            out.extend(self.other_lines(o))
        out.append("\\end{tikzpicture}")
        return "\n".join(out) + "\n"

    def sign_lines(self):
        """Put each sign beside the input it belongs to (textbook placement)."""
        lines = []
        for n in self.nodes.values():
            if n.style != "sum" or not n.signs:
                continue
            entries = []
            for e in self.edges:
                p = e.points[-1] if e.arrow in ("->", "<->") else e.points[0]
                glued = e.end if e.arrow in ("->", "<->") else e.start
                if glued == n.sid or math.dist(p, (n.cx, n.cy)) < 0.6 * n.w + 0.1:
                    ang = math.atan2(p[1] - n.cy, p[0] - n.cx)
                    entries.append(ang)
            free = list(entries)
            for sign, sx, sy in n.signs:
                if free:
                    sa = math.atan2(sy - n.cy, sx - n.cx)
                    ang = min(free, key=lambda a: abs(math.remainder(a - sa, 2 * math.pi)))
                    free.remove(ang)
                    ang -= math.pi / 4  # beside the arrow: 45 degrees clockwise
                else:
                    ang = math.atan2(sy - n.cy, sx - n.cx)
                r = n.w / 2 + 0.2
                shift = "(%s,%s)" % (_fmt(r * math.cos(ang)), _fmt(r * math.sin(ang)))
                lines.append("\\node[sign] at ([shift={%s}]%s.center) {$%s$};" % (shift, n.name, sign))
        return lines

    def other_lines(self, o):
        x0, y0, x1, y1 = o.x, o.y - o.h, o.x + o.w, o.y
        if o.prst == "rightBrace":
            return ["\\draw[decorate, decoration={brace, amplitude=4pt}] %s -- %s;" % (_pt((x0, y1)), _pt((x0, y0)))]
        if o.prst == "leftBrace":
            return ["\\draw[decorate, decoration={brace, amplitude=4pt}] %s -- %s;" % (_pt((x1, y0)), _pt((x1, y1)))]
        if not o.w or not o.h:
            return []
        return ["%% unsupported shape: %s" % (o.prst or "custom"),
                "\\draw %s rectangle %s;" % (_pt((x0, y0)), _pt((x1, y1)))]


def _plain(tex):
    return re.sub(r"[$\s{}]", "", tex).replace("\\pm", "\u00b1")


def _axis(a, b, tol=0.02):
    if abs(a[1] - b[1]) < tol:
        return "h"
    if abs(a[0] - b[0]) < tol:
        return "v"
    return None


def _median(values):
    v = sorted(values)
    return v[len(v) // 2]


# --------------------------------------------------------------------------
# Project files
# --------------------------------------------------------------------------

def ensure_styles(project):
    ddir = os.path.join(project, "diagrams")
    os.makedirs(ddir, exist_ok=True)
    styles = os.path.join(ddir, "tikzstyles.tex")
    if not os.path.exists(styles):
        with open(styles, "w", encoding="utf-8") as f:
            f.write(STYLES)
    main = os.path.join(project, "main.tex")
    if os.path.exists(main):
        text = open(main, encoding="utf-8").read()
        if "diagrams/tikzstyles" not in text:
            add = "\\usepackage{tikz}\n\\input{diagrams/tikzstyles}\n"
            if "\\graphicspath" in text:
                text = re.sub(r"(\\graphicspath\{.*?\}\}?\n)", lambda m: m.group(1) + add, text, count=1)
            else:
                text = text.replace("\\begin{document}", add + "\n\\begin{document}", 1)
            with open(main, "w", encoding="utf-8") as f:
                f.write(text)
    return ddir


def patch_slide(project, slide_no, j):
    """Replace \\includegraphics{slide_i_image_j} by \\input{diagrams/slide_i_diagram_j}."""
    path = os.path.join(project, "slides", f"slide_{slide_no}.tex")
    new = f"\\input{{diagrams/slide_{slide_no}_diagram_{j}}}"
    if not os.path.exists(path):
        return f"{path} not found; add {new} by hand"
    text = open(path, encoding="utf-8").read()
    if new in text:
        return "already uses the TikZ diagram"
    pattern = re.compile(r"^(\\includegraphics(\[[^\]]*\])?\{slide_%d_image_%d\})[ \t]*$" % (slide_no, j), re.M)
    if not pattern.search(text):
        return f"no \\includegraphics{{slide_{slide_no}_image_{j}}} line found; add {new} by hand"
    text = pattern.sub(lambda m: "% " + m.group(1) + "\n" + new, text, count=1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return "slide updated"


def parse_slides(tokens):
    numbers = []
    for tok in tokens:
        for part in re.split(r"[,\s]+", tok):
            if not part:
                continue
            m = re.search(r"(\d+)(?:\.tex)?$", part)
            if not m:
                raise SystemExit(f"cannot read a slide number from '{part}'")
            numbers.append(int(m.group(1)))
    return sorted(set(numbers))


def main(argv=None):
    ap = argparse.ArgumentParser(description="Redraw the diagrams of chosen slides as TikZ.")
    ap.add_argument("pptx", help="the original .pptx file")
    ap.add_argument("--slides", nargs="+", required=True,
                    help="slide numbers (22,50) or slide files (slide_22.tex)")
    ap.add_argument("--project", help="Beamer project made by pptx2beamer.py (default: <name>_beamer)")
    args = ap.parse_args(argv)

    prs = Presentation(args.pptx)
    project = args.project or os.path.splitext(args.pptx)[0] + "_beamer"
    reader = Reader(prs)
    ddir = None
    for n in parse_slides(args.slides):
        if not 1 <= n <= len(prs.slides):
            print(f"slide {n}: no such slide (the deck has {len(prs.slides)})")
            continue
        found = reader.diagrams(prs.slides[n - 1], n - 1)
        if not found:
            print(f"slide {n}: no diagram found")
        for j, items in found:
            if items is None:
                print(f"slide {n}, image {j}: skipped (drawn over a picture)")
                continue
            if not any(i.kind == "node" for i in items):
                print(f"slide {n}, image {j}: skipped (no blocks or boxes: not a block diagram)")
                continue
            if any(i.kind == "picture" for i in items):
                print(f"slide {n}, image {j}: skipped (contains a picture)")
                continue
            ddir = ddir or ensure_styles(project)
            tikz = Diagram(items).to_tikz()
            fname = os.path.join(ddir, f"slide_{n}_diagram_{j}.tex")
            with open(fname, "w", encoding="utf-8") as f:
                f.write(tikz)
            print(f"slide {n}, image {j}: wrote {os.path.relpath(fname, project)} ({patch_slide(project, n, j)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
